source 'https://rubygems.org'
#source 'http://production.cf.rubygems.org'
#source 'http://bundler-api.herokuapp.com'
 ruby '2.1.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.4'


#開発とテストで必要なもの
group :development, :test do
	gem 'sqlite3'
        #テストフレームワーク
	gem 'rspec-rails'
        #ファイルを監視してテストの自動化
        gem 'guard-rspec','2.5.0'
        #rspecの高速化 
        #インストールできなかったのでローカルでインストールしました
        #  sudo gem install -l ~/spork-1.0.0rc3.gem 
        #  sudo gem install -l ~/guard-spork-1.5.1.gem
        #  sudo gem install -l ~/spork-rails-4.0.0.gem 
        #  sudo gem install -l ~/childprocess-0.5.2.gem
        gem 'spork-rails', '4.0.0'
        gem 'guard-spork', '1.5.1'
        gem 'childprocess', '0.5.2'
        gem 'spork', '1.0.0rc3'
end

#テストで必要なもの
group :test do
	gem 'selenium-webdriver'
	gem 'capybara'
end

# Use sqlite3 as the database for Active Record

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

#group :production do
#	gem 'pg'
#	gem 'rails_12factor'
#end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
